name: ETL CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Uruchamianie codziennie o północy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: echo "NYT_API_KEY=${{ secrets.NYT_API_KEY }}" >> $GITHUB_ENV

    - name: Run ETL scripts
      run: |
        python scripts/last_month_articles.py
        python scripts/transform_headlines.py
        python scripts/analyze_headlines.py
        python scripts/bar_chart.py

    - name: Run tests
      run: |
        pytest
